import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";

import { label } from "../lib/crm";
import { errorMessage } from "../lib/errors";
import { apiFetch } from "../lib/api";
import { NOTE_KINDS, type CallNote } from "../lib/live";
import { FIELD_LABELS, postCallApi, type FieldStatus, type FollowUpDraft } from "../lib/postcall";
import { Card, QueryState } from "./common";
import { Alert, Button } from "./ui";

const STATUS_STYLE: Record<FieldStatus, string> = {
  CONFIRMED: "bg-emerald-100 text-emerald-800",
  INFERRED: "bg-amber-100 text-amber-800",
  NOT_DISCUSSED: "bg-slate-100 text-slate-500",
};

export function PostCallPanel({ callId }: { callId: string }) {
  const queryClient = useQueryClient();
  const data = useQuery({
    queryKey: ["post-call", callId],
    queryFn: () => postCallApi.get(callId),
    refetchInterval: (q) => (!q.state.data?.summary || q.state.data.summary.status === "PENDING" ? 3000 : false),
  });
  const notes = useQuery({
    queryKey: ["call-notes", callId],
    queryFn: () => apiFetch<CallNote[]>(`/api/v1/calls/${callId}/notes`),
  });
  const retry = useMutation({
    mutationFn: () => postCallApi.retry(callId),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["post-call", callId] }),
  });
  const summary = data.data?.summary;

  return (
    <QueryState isPending={data.isPending} error={data.error}>
      <div className="space-y-4">
        <Card title="Call summary">
          {!summary || summary.status === "PENDING" ? (
            <p className="text-sm text-slate-500">Preparing the summary…</p>
          ) : summary.status === "FAILED" ? (
            <div className="space-y-2">
              <Alert>The AI summary could not be generated ({summary.error_code}). The call record and transcript are safe.</Alert>
              <Button variant="secondary" disabled={retry.isPending} onClick={() => retry.mutate()}>
                Retry
              </Button>
            </div>
          ) : (
            <div className="space-y-3">
              <p className="text-sm text-slate-900">{summary.summary}</p>
              <dl className="grid gap-2 sm:grid-cols-2">
                {FIELD_LABELS.map(([key, text]) => {
                  const f = summary[key];
                  return (
                    <div key={key}>
                      <dt className="flex items-center gap-2 text-xs text-slate-500">
                        {text}
                        <span className={`rounded px-1.5 text-[10px] font-semibold ${STATUS_STYLE[f.status]}`}>
                          {f.status === "NOT_DISCUSSED" ? "NOT DISCUSSED" : f.status}
                        </span>
                      </dt>
                      <dd className="text-sm text-slate-900">{f.value ?? "—"}</dd>
                    </div>
                  );
                })}
              </dl>
              {summary.suggested_outcome ? (
                <p className="text-xs text-slate-500">
                  Suggested outcome (AI inference): {label(summary.suggested_outcome)}
                </p>
              ) : null}
              {summary.provider === "mock" ? (
                <p className="text-xs text-slate-400">Generated by the offline mock AI provider.</p>
              ) : null}
            </div>
          )}
        </Card>

        <Card title="Requirements, objections and notes">
          <QueryState isPending={notes.isPending} error={notes.error} empty={notes.data?.length === 0} emptyText="No structured notes.">
            <dl className="space-y-2">
              {NOTE_KINDS.map((k) => [k, (notes.data ?? []).filter((n) => n.kind === k)] as const)
                .filter(([, list]) => list.length)
                .map(([k, list]) => (
                  <div key={k}>
                    <dt className="text-xs font-medium text-slate-500">{label(k)}</dt>
                    {list.map((n) => (
                      <dd key={n.id} className="text-sm text-slate-900">
                        {n.category ? `${label(n.category)}: ` : ""}
                        {n.text}
                        {n.status === "SUGGESTED" ? <span className="ml-1 text-xs text-amber-700">(unreviewed)</span> : null}
                      </dd>
                    ))}
                  </div>
                ))}
            </dl>
          </QueryState>
        </Card>

        {data.data?.drafts.length ? (
          <Card title="Follow-up drafts">
            <p className="mb-3 text-xs text-slate-500">
              Drafts are never sent automatically. Review, edit and copy them into your email or WhatsApp.
            </p>
            <div className="space-y-3">
              {data.data.drafts.map((d) => (
                <DraftEditor key={d.id} callId={callId} draft={d} />
              ))}
            </div>
          </Card>
        ) : null}
      </div>
    </QueryState>
  );
}

function DraftEditor({ callId, draft }: { callId: string; draft: FollowUpDraft }) {
  const queryClient = useQueryClient();
  const [body, setBody] = useState(draft.body);
  const [copied, setCopied] = useState(false);
  const update = useMutation({
    mutationFn: (patch: Parameters<typeof postCallApi.reviewDraft>[2]) => postCallApi.reviewDraft(callId, draft.id, patch),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["post-call", callId] }),
  });
  const dirty = body !== draft.body;

  async function copy() {
    const text = draft.subject ? `${draft.subject}\n\n${body}` : body;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      update.mutate({ status: "COPIED" });
    } catch {
      setCopied(false);
    }
  }

  return (
    <article className="rounded-md border border-slate-200 p-3" aria-label={`${label(draft.channel)} draft`}>
      <div className="mb-2 flex items-center justify-between">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
          {draft.channel === "WHATSAPP" ? "WhatsApp" : label(draft.channel)} · {label(draft.status)}
        </p>
      </div>
      {draft.warnings.length ? (
        <div className="mb-2 rounded border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800" role="note">
          Please check before sending: {draft.warnings.join("; ")}
        </div>
      ) : null}
      {draft.subject ? <p className="mb-1 text-sm font-medium text-slate-900">{draft.subject}</p> : null}
      <textarea
        aria-label={`${label(draft.channel)} message`}
        className="block w-full rounded border border-slate-300 px-2 py-1 text-sm"
        rows={draft.channel === "EMAIL" ? 8 : 4}
        value={body}
        maxLength={5000}
        onChange={(e) => setBody(e.target.value)}
      />
      <div className="mt-2 flex flex-wrap gap-2">
        {dirty ? (
          <Button variant="secondary" disabled={update.isPending} onClick={() => update.mutate({ body })}>
            Save edits
          </Button>
        ) : null}
        <Button variant="secondary" disabled={dirty || update.isPending} onClick={() => update.mutate({ status: "APPROVED" })}>
          Approve
        </Button>
        <Button disabled={dirty} onClick={() => void copy()}>
          {copied ? "Copied" : "Copy"}
        </Button>
        <Button variant="secondary" onClick={() => update.mutate({ status: "DISCARDED" })}>
          Discard
        </Button>
      </div>
      {update.error ? <Alert>{errorMessage(update.error)}</Alert> : null}
    </article>
  );
}
