"""Migrations apply, roll back and match the ORM models (no drift)."""

from alembic import command

from tests.conftest import alembic_config


def test_downgrade_to_base_and_upgrade_again() -> None:
    cfg = alembic_config()
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")


def test_models_match_migrations() -> None:
    # Raises AutogenerateDiffsDetected if models and the migrated schema differ.
    command.check(alembic_config())
